### ISSUE TITLE
Gender  prediction cut-off threshold

### ISSUE THREAD

**Issue by LifeBytesDev** [adrianodemarino/Determine_sex_from_bam#2]
Hi, 

How did you decide the cutoff score for gender prediction?

**Comment by adrianodemarino** [comment]
Hi, 

That script is an old test that I have done. The cut-off coming from multiple observations, it's not so much accurate that threshold, maybe I should remove that or implement the new one.
Something more accurate is simply a numeric ratio of the X chromosome coverage (number of reads divided by sequence length) and the Y chromosome coverage. 
It looks like this:

X/Y ratio: 0.99

A ratio close to one indicates male, which a ratio that deviates from one indicates the sample is probably a female. 
Ranges for the two sexes are:

Male: 0.90-1.5
Female: 4.5-7.0

Adriano De Marino, PhD

**Comment by VivekTodur** [comment]
Hi Adriano,

thank you so much for the explanation.

**Comment by adrianodemarino** [comment]
@VivekTodur I have just updated the script with a new version, this should work better :)
